/**
 * 游戏平衡配置
 */

/** GPA相关配置 */
export const GPA_CONFIG = {
  HOLIDAY_MONTHS: [2, 7, 8],
  MONTHLY_DEDUCTION: 0.05,
  SKIP_CLASS_PROBABILITY: 0.3,
  SKIP_CLASS_DEDUCTION: 0.15,
};

/** 学业相关配置 */
export const ACADEMIC_CONFIG = {
  WARNING_THRESHOLD: 2.5,
  FAILED_COURSE_THRESHOLD: 3.0,
  WARNINGS_FOR_EXPULSION: 2,
  SCHOLARSHIP_THRESHOLD: 3.7,
  FAILURES_PER_WARNING: 3,
};
